idf_component_register(
    SRCS
        "main.c"
        "terminal.c"
        "term_render.c"
        "terminal_font.c"
        "keymap.c"
        "keycaps.c"
        "keystore.c"
        "hosts.c"
        "ssh_client.c"
        "ui.c"
    PRIV_REQUIRES
        esp_lcd
        esp_timer
        esp_app_format
        app_update
        esp_netif
        nvs_flash
        mbedtls
        lwip
        badge-bsp
        tanmatsu-wifi
        libssh2
        qrcode
    INCLUDE_DIRS
        "."
)
