// SPDX-License-Identifier: MIT
//
// An 8x16 bitmap font with the coverage a terminal needs: Latin, Greek,
// Cyrillic, punctuation, arrows, maths, box drawing and block elements.
// Generated by tools/make_font.py; the glyphs are GNU Unifont (SIL OFL-1.1).

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "pax_types.h"

#define TERMINAL_FONT_WIDTH  8
#define TERMINAL_FONT_HEIGHT 16

extern pax_font_t const terminal_font_raw;
#define terminal_font (&terminal_font_raw)

// True when the font can draw this codepoint. Anything else has to be replaced
// before drawing, because PAX advances by nothing for a glyph it does not have.
bool terminal_font_has_glyph(uint32_t codepoint);
