// SPDX-License-Identifier: MIT
//
// An 8x16 bitmap font for the terminal, with 16x16 glyphs for the East Asian
// characters that occupy two columns. Generated by tools/make_font.py; the
// glyphs are GNU Unifont (SIL OFL-1.1) and the cell widths come from the
// Unicode East Asian Width data file.

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "pax_types.h"

#define TERMINAL_FONT_WIDTH  8
#define TERMINAL_FONT_HEIGHT 16

extern pax_font_t const terminal_font_raw;
#define terminal_font (&terminal_font_raw)

// True when the font can draw this codepoint. Anything else has to be replaced
// before drawing, because PAX advances by nothing for a glyph it does not have.
bool terminal_font_has_glyph(uint32_t codepoint);

// How many columns the character occupies: 2 for East Asian Wide and Fullwidth,
// 1 for everything else. This is a Unicode property and does not depend on
// whether the font has a glyph, because the host counts columns the same way.
int terminal_char_width(uint32_t codepoint);
