#!/usr/bin/env python3
"""Turn GNU Unifont's .hex into a PAX bitmap font for the terminal.

Unifont is dual licensed GPLv2+ (with the font embedding exception) and
SIL OFL-1.1; this project uses it under the OFL. Only the 8x16 glyphs are
taken: the 16x16 double width ones would need wide cell handling in the
terminal, which it does not have yet.

Usage: make_font.py <unifont.hex> <out.c> <out.h>
"""

import sys

# What a terminal actually needs: the Latin alphabets, Greek and Cyrillic,
# punctuation, arrows, maths, and the box drawing and block characters that
# every TUI is built from.
RANGES = [
    (0x0020, 0x00FF, "Basic Latin and Latin-1"),
    (0x0100, 0x017F, "Latin Extended-A"),
    (0x0180, 0x024F, "Latin Extended-B"),
    (0x0250, 0x02AF, "IPA extensions"),
    (0x02B0, 0x02FF, "Spacing modifiers"),
    (0x0300, 0x036F, "Combining diacriticals"),
    (0x0370, 0x03FF, "Greek and Coptic"),
    (0x0400, 0x04FF, "Cyrillic"),
    (0x0500, 0x052F, "Cyrillic supplement"),
    (0x2000, 0x206F, "General punctuation"),
    (0x2070, 0x209F, "Super- and subscripts"),
    (0x20A0, 0x20BF, "Currency symbols"),
    (0x2100, 0x214F, "Letterlike symbols"),
    (0x2150, 0x218F, "Number forms"),
    (0x2190, 0x21FF, "Arrows"),
    (0x2200, 0x22FF, "Mathematical operators"),
    (0x2300, 0x23FF, "Miscellaneous technical"),
    (0x2400, 0x243F, "Control pictures"),
    (0x2500, 0x257F, "Box drawing"),
    (0x2580, 0x259F, "Block elements"),
    (0x25A0, 0x25FF, "Geometric shapes"),
    (0x2600, 0x26FF, "Miscellaneous symbols"),
    (0x2700, 0x27BF, "Dingbats"),
    (0xFFFD, 0xFFFD, "Replacement character"),
]

WIDTH = 8
HEIGHT = 16

# PAX reads the leftmost pixel from the least significant bit; Unifont writes
# it in the most significant one.
REVERSE = [int(f"{n:08b}"[::-1], 2) for n in range(256)]


def load_hex(path):
    glyphs = {}
    with open(path, "r", encoding="ascii") as handle:
        for line in handle:
            line = line.strip()
            if not line or ":" not in line:
                continue
            code, bits = line.split(":", 1)
            if len(bits) != HEIGHT * 2:
                continue  # A double width glyph; skipped, see the docstring
            glyphs[int(code, 16)] = bytes(
                REVERSE[int(bits[i:i + 2], 16)] for i in range(0, len(bits), 2)
            )
    return glyphs


def main():
    if len(sys.argv) != 4:
        print(__doc__, file=sys.stderr)
        return 1

    glyphs = load_hex(sys.argv[1])
    blank = bytes(HEIGHT)

    out = []
    out.append("// SPDX-License-Identifier: MIT")
    out.append("//")
    out.append("// Generated by tools/make_font.py from GNU Unifont; do not edit.")
    out.append("// The glyph data is GNU Unifont, used under SIL OFL-1.1.")
    out.append("")
    out.append('#include "terminal_font.h"')
    out.append("")

    total = 0
    for start, end, name in RANGES:
        out.append(f"// {name}: U+{start:04X}..U+{end:04X}")
        out.append(f"static uint8_t const glyphs_{start:04x}[] = {{")
        for code in range(start, end + 1):
            data = glyphs.get(code, blank)
            body = ", ".join(f"0x{b:02X}" for b in data)
            out.append(f"    {body},  // U+{code:04X}")
            total += 1
        out.append("};")
        out.append("")

    out.append("static pax_font_range_t const terminal_ranges[] = {")
    for start, end, name in RANGES:
        out.append("    {")
        out.append("        .type  = PAX_FONT_TYPE_BITMAP_MONO,")
        out.append(f"        .start = 0x{start:05X},")
        out.append(f"        .end   = 0x{end:05X},")
        out.append("        .bitmap_mono =")
        out.append("            {")
        out.append(f"                .glyphs = glyphs_{start:04x},")
        out.append(f"                .width  = {WIDTH},")
        out.append(f"                .height = {HEIGHT},")
        out.append("                .bpp    = 1,")
        out.append("            },")
        out.append("    },")
    out.append("};")
    out.append("")
    out.append("pax_font_t const terminal_font_raw = {")
    out.append('    .name         = "Unifont 8x16",')
    out.append("    .n_ranges     = sizeof(terminal_ranges) / sizeof(terminal_ranges[0]),")
    out.append("    .ranges       = terminal_ranges,")
    out.append(f"    .default_size = {HEIGHT},")
    out.append("    .recommend_aa = false,")
    out.append("};")
    out.append("")
    out.append("bool terminal_font_has_glyph(uint32_t codepoint) {")
    out.append("    for (size_t i = 0; i < sizeof(terminal_ranges) / sizeof(terminal_ranges[0]); i++) {")
    out.append("        if (codepoint >= terminal_ranges[i].start && codepoint <= terminal_ranges[i].end) {")
    out.append("            return true;")
    out.append("        }")
    out.append("    }")
    out.append("    return false;")
    out.append("}")
    out.append("")

    with open(sys.argv[2], "w", encoding="ascii") as handle:
        handle.write("\n".join(out))

    header = f"""// SPDX-License-Identifier: MIT
//
// An 8x16 bitmap font with the coverage a terminal needs: Latin, Greek,
// Cyrillic, punctuation, arrows, maths, box drawing and block elements.
// Generated by tools/make_font.py; the glyphs are GNU Unifont (SIL OFL-1.1).

#pragma once

#include <stdbool.h>
#include <stdint.h>
#include "pax_types.h"

#define TERMINAL_FONT_WIDTH  {WIDTH}
#define TERMINAL_FONT_HEIGHT {HEIGHT}

extern pax_font_t const terminal_font_raw;
#define terminal_font (&terminal_font_raw)

// True when the font can draw this codepoint. Anything else has to be replaced
// before drawing, because PAX advances by nothing for a glyph it does not have.
bool terminal_font_has_glyph(uint32_t codepoint);
"""
    with open(sys.argv[3], "w", encoding="ascii") as handle:
        handle.write(header)

    print(f"{total} glyphs, {total * HEIGHT} bytes of bitmap data", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
